package HeroMaker;


import java.util.Arrays;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fidyle
 */
public class MainHeroMaker extends javax.swing.JFrame {

    /**
     * Creates new form MainHeroMaker
     */
    EntityManagerFactory emf = null;
    EntityManager em = null;
    public MainHeroMaker() {
        initComponents();
        connectDatabase();
        updateHeroTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSearch = new javax.swing.JTextField();
        jLabelTableTitle = new javax.swing.JLabel();
        jLabelSearchTitle = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jScrollPaneTableHeroList = new javax.swing.JScrollPane();
        jTableHeroList = new javax.swing.JTable();
        jMenuTop = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileNew = new javax.swing.JMenuItem();
        jMenuFileSeparator = new javax.swing.JPopupMenu.Separator();
        jMenuFileExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));

        jTextFieldSearch.setToolTipText("hero name");

        jLabelTableTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTableTitle.setText("List of local Heroes");

        jLabelSearchTitle.setText("Search by name");

        jButtonSearch.setText("Search");

        jTableHeroList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Creator", "Race", "Class", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHeroList.setToolTipText("Double click on a line to load a hero");
        jTableHeroList.getTableHeader().setReorderingAllowed(false);
        jTableHeroList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHeroListMouseClicked(evt);
            }
        });
        jScrollPaneTableHeroList.setViewportView(jTableHeroList);

        jMenuFile.setText("File");

        jMenuFileNew.setText("New Hero");
        jMenuFile.add(jMenuFileNew);
        jMenuFile.add(jMenuFileSeparator);

        jMenuFileExit.setText("Exit");
        jMenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuFileExit);

        jMenuTop.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuTop.add(jMenuEdit);

        jMenuHelp.setText("Help");
        jMenuTop.add(jMenuHelp);

        setJMenuBar(jMenuTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPaneTableHeroList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTableTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelSearchTitle)
                            .addGap(38, 38, 38)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabelTableTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearchTitle)
                    .addComponent(jButtonSearch))
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneTableHeroList, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileExitActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit now ?", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuFileExitActionPerformed

    private void jTableHeroListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHeroListMouseClicked
        // TODO add your handling code here:
        int row = jTableHeroList.rowAtPoint(evt.getPoint());
        int col = jTableHeroList.columnAtPoint(evt.getPoint());
        if(col == 5){
            System.out.println("okay");
        }
    }//GEN-LAST:event_jTableHeroListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHeroMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHeroMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHeroMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHeroMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHeroMaker().setVisible(true);
            }
        });
    }
    public void connectDatabase(){
        if(emf == null){
            emf = javax.persistence.Persistence.createEntityManagerFactory("HeroMakerPU");
        }
        if(em == null){
            em = emf.createEntityManager();
        }
    }
    public void updateHeroTable(){
        ClassJpaController classController = new ClassJpaController(emf);
        HeroJpaController heroController = new HeroJpaController(emf);
        RaceJpaController raceController = new RaceJpaController(emf);
        
        List<Hero> heroList = heroController.findHeroEntities();
        
        Object[][] finalList = new Object[heroList.size()][5];
        Object[] finalListPart = new Object[5];
        String aClass, aRace;
        int k = 0, aLevel;
       
        for(Hero aHero: heroList){
           
           aClass = classController.findClass(aHero.getLevel().getLevelPK().getIdClass()).getName();
           aRace = raceController.findRace(aHero.getIdRace().getId()).getName();
           aLevel = aHero.getLevel().getLevelPK().getId();
           
           finalListPart = new Object[]{aHero.getName(), aHero.getCreator(), aRace, aClass, aLevel};
           finalList[k] = finalListPart;
           
           k++;
        }
        
        DefaultTableModel tableModel = (DefaultTableModel) jTableHeroList.getModel();
        //Deletes all rows
        tableModel.setRowCount(0);
        tableModel.setDataVector(finalList, new Object[]{"Name","Creator","Race","Class","Level"});
        //Object[][] list = new Object[][]{{"name","creator","race","class",1,"test"},{"name","creator","race","class",1,"test"}};
        //tableModel.addRow(new Object[]{"name","creator","race","class",1,test});
        
        jTableHeroList.setModel(tableModel);
        
        classController = null;
        heroController = null;
        raceController = null;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelSearchTitle;
    private javax.swing.JLabel jLabelTableTitle;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFileExit;
    private javax.swing.JMenuItem jMenuFileNew;
    private javax.swing.JPopupMenu.Separator jMenuFileSeparator;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuBar jMenuTop;
    private javax.swing.JScrollPane jScrollPaneTableHeroList;
    private javax.swing.JTable jTableHeroList;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
