CREATE TABLE RACE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);
CREATE TABLE HERO (
    ID INTEGER NOT NULL,
    CREATOR VARCHAR(255),
    NAME VARCHAR(255),
    ID_RACE INTEGER,
    ID_LEVEL INTEGER,
    ID_CLASS INTEGER,
    PRIMARY KEY (ID)
);
CREATE TABLE CLASS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    RESSOURCE_NAME VARCHAR(255),
    PRIMARY KEY (ID)
);
CREATE TABLE LEVEL (
    CHARISM INTEGER,
    DEXTERITY INTEGER,
    STRENGTH INTEGER,
    WISDOM INTEGER,
    HEALTH INTEGER,
    RESSOURCE INTEGER,
    ID_CLASS INTEGER NOT NULL,
    ID INTEGER NOT NULL,
    PRIMARY KEY (ID_CLASS, ID)
);
CREATE TABLE SPELL (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DAMAGE INTEGER NOT NULL,
    ELEMENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE ACQUIRE (
    ID_LEVEL INTEGER,
    ID_CLASS INTEGER,
    ID_SPELL INTEGER,
    PRIMARY KEY (ID_LEVEL, ID_CLASS,ID_SPELL)
);

ALTER TABLE HERO ADD CONSTRAINT FK_HERO_ID_RACE FOREIGN KEY (ID_RACE) REFERENCES RACE (ID);
ALTER TABLE HERO ADD CONSTRAINT FK_HERO_ID_CLASS FOREIGN KEY (ID_CLASS, ID_LEVEL) REFERENCES LEVEL (ID_CLASS, ID);
ALTER TABLE LEVEL ADD CONSTRAINT FK_LEVEL_ID_CLASS FOREIGN KEY (ID_CLASS) REFERENCES CLASS (ID);
ALTER TABLE ACQUIRE ADD CONSTRAINT FK_ACQUIRE_ID_CLASS FOREIGN KEY (ID_CLASS, ID_LEVEL) REFERENCES LEVEL (ID_CLASS, ID);
ALTER TABLE ACQUIRE ADD CONSTRAINT FK_ACQUIRE_ID_SPELL FOREIGN KEY (ID_SPELL) REFERENCES SPELL (ID);